# apiVersion: cert-manager.io/v1
# kind: Issuer
# metadata:
#   name: swimlane
#   namespace: swimlane
# spec:
#   acme:
#     # The ACME server URL
#     server: https://acme-staging-v02.api.letsencrypt.org/directory
#     # Email address used for ACME registration
#     email: isaacsmothers@yahoo.com
#     # Name of a secret used to store the ACME account private key
#     privateKeySecretRef:
#       name: swimlane
#     # Enable the HTTP-01 challenge provider
#     solvers:
#     # An empty 'selector' means that this solver matches all domains
#     - selector: {}
#       http01:
#         ingress:
#           class: nginx

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}