apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-mongo
  labels:
    app: {{ .Values.name }}-mongo
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.mongoService.externalPort }}
    targetPort: {{ .Values.mongoService.internalPort }}
    protocol: TCP
    name: "http-{{ .Values.name }}-mongo"
  selector:
    app: {{ .Values.name }}-mongo