---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-mongo
spec:
  replicas: {{ .Values.mongoReplicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}-mongo
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-mongo
    spec:
      containers:
        - name: {{ .Values.name }}-mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
            